# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Register(QtCore.QObject):
    def __init__(self,window):
        super(Ui_Register,self).__init__()
        self.window = window
        self.setupUi()
    def setupUi(self):
        self.window.setObjectName("Form")
        self.window.resize(800, 600)
        self.start = QtWidgets.QPushButton(self.window)
        self.start.setGeometry(QtCore.QRect(300, 520, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(self.window)
        self.label.setGeometry(QtCore.QRect(290, 10, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 90, 391, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setBaseSize(QtCore.QSize(0, 0))
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.password1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password1.setObjectName("passowrd1")
        self.gridLayout.addWidget(self.password1, 1, 1, 1, 1)
        self.password2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password2.setObjectName("password2")
        self.gridLayout.addWidget(self.password2, 2, 1, 1, 1)
        self.address = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.address.setEnabled(True)
        self.address.setTabletTracking(False)
        self.address.setObjectName("address")
        self.gridLayout.addWidget(self.address, 3, 1, 1, 1)
        self.age = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.age.setMaximum(150)
        self.age.setObjectName("age")
        self.gridLayout.addWidget(self.age, 4, 1, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.window)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.window.setWindowTitle(_translate("Form", "Form"))
        self.start.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "REGISTER"))
        self.label_5.setText(_translate("Form", "  Address:"))
        self.label_4.setText(_translate("Form", "  password2:  "))
        self.label_2.setText(_translate("Form", "  name:   "))
        self.label_3.setText(_translate("Form", "  password1:  "))
        self.label_6.setText(_translate("Form", "  age:     "))
