# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeui.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets,Qt

class Ui_Change(QtCore.QObject):
    def __init__(self,window):
        super(Ui_Change,self).__init__()
        self.window = window
        self.setupUi()
    def setupUi(self):
        css =open('./beautify/css.qss','r')#加载外部qss文件美化
        str = css.readlines()
        str =''.join(str).strip('\n')
        QtWidgets.qApp.setStyleSheet(str)
        self.window.setObjectName("Dialog")
        self.window.resize(800, 600)
        self.label = QtWidgets.QLabel(self.window)
        self.label.setGeometry(QtCore.QRect(230, 37, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.change = QtWidgets.QPushButton(self.window)
        self.change.setGeometry(QtCore.QRect(320, 510, 112, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.change.setFont(font)
        self.change.setObjectName("change")
        self.password1 = QtWidgets.QLineEdit(self.window)
        self.password1.setGeometry(QtCore.QRect(390, 180, 193, 35))
        self.password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1.setObjectName("password1")
        self.address = QtWidgets.QLineEdit(self.window)
        self.address.setGeometry(QtCore.QRect(390, 360, 193, 35))
        self.address.setObjectName("address")
        self.password2 = QtWidgets.QLineEdit(self.window)
        self.password2.setGeometry(QtCore.QRect(390, 240, 193, 35))
        self.password2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2.setObjectName("password2")
        self.name = QtWidgets.QLineEdit(self.window)
        self.name.setGeometry(QtCore.QRect(390, 121, 193, 35))
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(self.window)
        self.label_3.setGeometry(QtCore.QRect(191, 180, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.window)
        self.label_2.setGeometry(QtCore.QRect(191, 121, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.window)
        self.label_5.setGeometry(QtCore.QRect(190, 241, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.window)
        self.label_4.setGeometry(QtCore.QRect(191, 300, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.window)
        self.label_6.setGeometry(QtCore.QRect(191, 360, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.age = QtWidgets.QLineEdit(self.window)
        self.age.setGeometry(QtCore.QRect(390, 300, 193, 35))
        self.age.setObjectName("age")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.window)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.window.setWindowTitle(_translate("Dialog", "ChangeInfo"))
        self.label.setText(_translate("Dialog", "Change Infomation"))
        self.change.setText(_translate("Dialog", "Change"))
        self.label_3.setText(_translate("Dialog", "password1"))
        self.label_2.setText(_translate("Dialog", "name"))
        self.label_5.setText(_translate("Dialog", "password2"))
        self.label_4.setText(_translate("Dialog", "age"))
        self.label_6.setText(_translate("self.window", "address"))
