from PyQt5 import QtCore,QtWidgets,QtGui
from PyQt5.QtWidgets import QMessageBox
class Ui_Login(QtCore.QObject):
    def __init__(self,window):
        super(Ui_Login,self).__init__()
        self.window = window
        self.setupUi()
    def setupUi(self):
        css =open('./beautify/css.qss','r')#加载外部qss文件美化
        str = css.readlines()
        str =''.join(str).strip('\n')
        QtWidgets.qApp.setStyleSheet(str)
        self.window.setObjectName("MainWindow")
        self.window.resize(600, 450)
        self.centralwidget = QtWidgets.QWidget(self.window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 470, 90))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(190, 150, 200, 35))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(190, 230, 200, 35))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 100, 30))
        self.isvisi = QtWidgets.QRadioButton(self.centralwidget)
        self.isvisi.setGeometry(QtCore.QRect(420, 270, 151, 51))
        self.isvisi.setObjectName("isvisi")
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 230, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.register = QtWidgets.QPushButton(self.centralwidget)
        self.register.setGeometry(QtCore.QRect(420, 150, 112, 34))
        self.register.setObjectName("register_2")
        self.follow = QtWidgets.QPushButton(self.centralwidget)
        self.follow.setGeometry(QtCore.QRect(420, 230, 112, 34))
        self.follow.setObjectName("follow")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(240, 320, 112, 34))
        self.login.setObjectName("login")
        self.window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 30))
        self.menubar.setObjectName("menubar")
        self.window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.window)
        self.statusbar.setObjectName("statusbar")
        self.window.setStatusBar(self.statusbar)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.window)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.window.setWindowTitle(_translate("MainWindow", "login"))
        self.label.setText(_translate("MainWindow", "Ty\'s Online Chatting Room"))
        self.label_2.setText(_translate("MainWindow", "昵称"))
        self.label_3.setText(_translate("MainWindow", "密码"))
        self.register.setText(_translate("MainWindow", "注册账号"))
        self.follow.setText(_translate("MainWindow", "关注我"))
        self.login.setText(_translate("MainWindow", "登陆"))
        self.isvisi.setText(_translate("MainWindow", "隐身登陆"))
