# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerui.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Register(object):
    def __init__(self,window):
        super(Ui_Register,self).__init__()
        self.window = window
        self.setupUi()
    def setupUi(self):
        self.window.setObjectName("Form")
        self.window.resize(800, 600)
        self.start = QtWidgets.QPushButton(self.window)
        self.start.setGeometry(QtCore.QRect(330, 520, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(self.window)
        self.label.setGeometry(QtCore.QRect(290, 10, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.window)
        self.label_5.setGeometry(QtCore.QRect(211, 346, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.window)
        self.label_4.setGeometry(QtCore.QRect(211, 276, 148, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.window)
        self.label_2.setGeometry(QtCore.QRect(211, 136, 110, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.window)
        self.label_3.setGeometry(QtCore.QRect(211, 206, 148, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.window)
        self.label_6.setGeometry(QtCore.QRect(211, 416, 116, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica-Condensed-Black-Se")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.name = QtWidgets.QLineEdit(self.window)
        self.name.setGeometry(QtCore.QRect(368, 136, 193, 41))
        self.name.setBaseSize(QtCore.QSize(0, 0))
        self.name.setObjectName("name")
        self.password1 = QtWidgets.QLineEdit(self.window)
        self.password1.setGeometry(QtCore.QRect(368, 206, 193, 41))
        self.password1.setObjectName("passowrd1")
        self.password2 = QtWidgets.QLineEdit(self.window)
        self.password2.setGeometry(QtCore.QRect(368, 276, 193, 41))
        self.password2.setObjectName("password2")
        self.address = QtWidgets.QLineEdit(self.window)
        self.address.setEnabled(True)
        self.address.setGeometry(QtCore.QRect(368, 346, 193, 41))
        self.address.setTabletTracking(False)
        self.address.setObjectName("address")
        self.age = QtWidgets.QSpinBox(self.window)
        self.age.setGeometry(QtCore.QRect(368, 416, 58, 41))
        self.age.setMaximum(150)
        self.age.setObjectName("age")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.window)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.window.setWindowTitle(_translate("Form", "Register"))
        self.start.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "REGISTER"))
        self.label_5.setText(_translate("Form", "  Address:"))
        self.label_4.setText(_translate("Form", "  password2:  "))
        self.label_2.setText(_translate("Form", "  name:   "))
        self.label_3.setText(_translate("Form", "  password1:  "))
        self.label_6.setText(_translate("Form", "  age:     "))
